name: my_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase 
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_messaging: ^15.0.1

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^5.8.0+1

  # Dependency Injection
  get_it: ^7.6.4

  # Routing
  go_router: ^16.0.0

  # UI
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  persistent_bottom_nav_bar: ^6.2.1

  # Utils
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  meta: ^1.16.0
  intl: 

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/categories/
    - assets/onboarding/
    - assets/images/
    - assets/icons/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
